### PR TITLE
Add Fuzer

### PR DESCRIPTION
**Pull request by yotamN**

### CODE REVIEW

**Comment by HDVinnie** [comment]
@yotamN your missing columns like grade and codebase.

**Comment by yotamN** [comment]
I think I have added it all now. I'm not sure how to define join diff and I'm not sure what the codebase is, it seems something on top of vbulletin.

**Comment by HDVinnie** [comment]
@yotamN you are missing Birthdate....if you do not know the values simply use a `-`

**Comment by gunysa1** [comment]
{"Name": "Fuzer", "Abbreviation": "FUZ", "Type": "General, Hebrew", "Codebase": "Custom", "Observatory Grade": "B", "Users": "16,151", "Torrents": "86,996", "Peers": "91,729", "Ratio": "Yes", "Ratio Diff": "Medium", "Freeleech": "Yes", "Points": "Yes", "Hit & Run": "Yes", "Birthdate": "2013", "Join": "Invite, Application ", "Join Diff": "Easy", "Updated": "2021-09-21"}

**Pull request closed without merging**
